### PR TITLE
fix: Handle errors for Brazil farm create order prompt

### LINKED ISSUE #288: Handle errors for Brazil farm create order prompt in UI for scenarios with 500 status code
Handle errors for Brazil  farm create order prompt in UI for scenarios with 500 status code because badge is not assigned.
Improve error/exception handling around identity.

```
curl -X POST http://127.0.0.1:8000/agent/prompt \
  -H "Content-Type: application/json" \
  -d '{
    "prompt": "I would like to buy 200 lbs quantity of coffee at USD 500 price from Brazil"
  }'   
Status code: 500
{"detail":"Operation failed: Identity verification failed for farm 'Brazil Coffee Farm'. Details: Identity verification failed for farm Brazil Coffee Farm: No matching app found, this farm does not have identity service enabled."}
```
UI issues: 
Image

### PR DESCRIPTION
**Pull request by shanchunyang0919**
# Description

- **Simplified error messages**: Removed redundant farm name repetition in backend error chains, making logs cleaner and more readable
- **Enhanced frontend error display**: Extracts and shows detailed server error messages from Axios responses instead of generic error text
- **Better user feedback**: Users now see specific error details like "No matching identity app service found" instead of generic failure messages
Screenshot 2025-11-25 at 8 22 09 AM

## Issue Link

Fixes #288 

## Type of Change

- [X] Bugfix
- [ ] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [ ] I have read the [contributing guidelines](/agntcy/coffeeAgntcy/blob/main/CONTRIBUTING.md)
- [X] Existing issues have been referenced (where applicable)
- [ ] I have verified this change is not present in other open pull requests
- [ ] Functionality is documented
- [ ] All code style checks pass
- [ ] New code contribution is covered by automated tests
- [ ] All new and existing tests pass

### CODE REVIEW

File: coffeeAGNTCY/coffee_agents/lungo/frontend/src/components/Chat/ChatArea.tsx [hunk 1]
```diff
@@ -115,8 +116,16 @@ const ChatArea: React.FC<ChatAreaProps> = ({
         },
         onError: (error) => {
           logger.apiError("/agent/prompt", error)
+
+          // Extract error message from AxiosError or use fallback
+          let errorMessage = "Sorry, I encountered an error"
+          if (axios.isAxiosError(error) && error.response?.data?.detail) {
+            console.log("API error response:", error.response.data)
```
Comment (Shridhar-2205) [inline coffeeAGNTCY/coffee_agents/lungo/frontend/src/components/Chat/ChatArea.tsx:123]: q: how does it handle 500s

**Review by nandu-gh — APPROVED** [review]

File: coffeeAGNTCY/coffee_agents/lungo/frontend/src/components/Chat/ChatArea.tsx (hunk 1 above)
Comment (shanchunyang0919) [reply coffeeAGNTCY/coffee_agents/lungo/frontend/src/components/Chat/ChatArea.tsx:123]: Hi @Shridhar-2205, I dug into the code and it seems the UI is already set up to handle 500 errors—it's just not properly propagating the error details from the server to the client.

**Review by Shridhar-2205 — APPROVED** [review]
